### ISSUE TITLE
Creating a User Scenerio & Mockup on a User Reviewing a Post on the Forum

### ISSUE THREAD

**Issue by mberkturgut** [bounswe/bounswe2022group6#33]
As decided on [meeting 5](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%235-03.20.2022#action-items), a persona, the pre-conditions of the scenerio, step by step actions actions and the acceptance criteria on a Doctor-type user reviewing a post on forum will be listed in [User Scenarios & Mockups](https://github.com/bounswe/bounswe2022group6/wiki/User-Scenarios-&-Mockups) page. [Mocqups](https://mocqups.com) will be used to create a mockup.

**Comment by LehabuL** [comment]
I changed the [User Scenarios & Mockups](https://github.com/bounswe/bounswe2022group6/wiki/User-Scenarios-&-Mockups) page. Please use the new page that I created that is located in this [link](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%233:-Reviewing-a-Post-on-the-Forum). For your information, @BPamukcuoglu, @berfinsimsekk, @yusuferdemnacar, @mberkturgut.

**Comment by mberkturgut** [comment]
👍 Thanks! @LehabuL

**Comment by yusuferdemnacar** [comment]
I added the mockup images to the scenario page. You can find them [here](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%233:-Reviewing-a-Post-on-the-Forum#mockups).
I am now closing this issue since it is done, please reopen this issue and comment on your changes if you edit/add/change anything.
