### ISSUE TITLE
Create post preview 

### ISSUE THREAD

**Issue by aeren02** [bounswe/bounswe2022group6#375]
Since the current post preview doesn't view images, a sufficient method must be added in no time.

**Comment by aeren02** [comment]
Since the image dimensions can change between examples, I researched a way to scale the image into it's original size using newly added functions from react-native.

**Comment by aeren02** [comment]
Due to time and communication issues, a substitute post preview mechanism has been written by other mobile members, so this commit will wait until due time.

**Comment by araldortogul** [comment]
> Since the current post preview doesn't view images, a sufficient method must be added in no time.

I have implemented and added post previews while implementing home feed with PR #270 almost a month ago, and they show images if the post has any.
Since the current post preview component satisfies the [requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1223-post-previews), there is no need to focus on post previews for now.
