### ISSUE TITLE
Sequence Diagram: Account Edit

### ISSUE THREAD

**Issue by iremmer** [bounswe/bounswe2022group6#81]
The sequence diagram of the Editing Account process should be designed.

@LehabuL is the reviewer of this task.
Deadline: 10.04.2022

**Comment by iremmer** [comment]
I have completed the sequence diagram of the "Edit Account" action. 
@LehabuL can you please check it?

**Comment by LehabuL** [comment]
For change mail address case use should plug in the verification code before Frontend sending setMailAddress. Also I believe showing different topics in a more appropriate manner would be better since in this sequence, user is changing nearly every field of their account. We can focus on this more after we have our customer meeting this Wednesday with more clarifications.

**Comment by LehabuL** [comment]
We did the necessary updates.
